# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TextVersionJS
email: info@edmdesigner.com
description: > # this means to ignore newlines until "baseurl:"
  With textversion.js you can easily generate the text version of an HTML email.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://textversionjs.com" # the base hostname & protocol for your site
gaCode: UA-42954042-7
twitter_username: EDMdesigner
github_username:  EDMdesigner

# Build settings
markdown: kramdown
